version: '3.7'

services:
  flask:
    build: .
    env_file: user_key.env
    volumes:
      - ./flask:/home/lunch/flask
      - ./lunch_report:/home/lunch/lunch_report
      - ./config:/home/lunch/config
    ports:
      - "5000:5000"
    container_name: lunch
